import { precacheAndRoute } from 'workbox-precaching';
import { set } from 'idb-keyval';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('fetch', (event) => {
    // Intercept the /share-target route from the Web Share Target API manifest
    if (event.request.method === 'POST' && event.request.url.endsWith('/share-target')) {
        event.respondWith(
            (async () => {
                try {
                    const formData = await event.request.formData();
                    const files = formData.getAll('media');

                    if (files && files.length > 0) {
                        // Save the first image in IndexedDB to be picked up by the React app
                        await set('shared-image', files[0]);
                    }

                    // Redirect to the home page so the SPA loads normally
                    return Response.redirect('/?shared=true', 303);
                } catch (error) {
                    console.error('Error handling share target:', error);
                    return Response.redirect('/?share-error=true', 303);
                }
            })()
        );
    }
});
